import React from 'react';
import { NavTab, Note, StudyStats } from '../types';
import {
  Clock,
  BookOpen,
  Brain,
  Layers,
  ArrowRight,
  Flame,
  CheckCircle2,
  Sparkles,
  Zap,
  Target
} from 'lucide-react';

interface HomeOverviewProps {
  onSelectTab: (tab: NavTab) => void;
  onOpenNoteForQuiz: (note: Note) => void;
  notes: Note[];
  stats: StudyStats;
}

export const HomeOverview: React.FC<HomeOverviewProps> = ({
  onSelectTab,
  onOpenNoteForQuiz,
  notes,
  stats,
}) => {
  const heroImage = '/src/assets/images/hero_studyspace_ambient_1791201211167.jpg';
  const notesCardImage = '/src/assets/images/card_notes_journal_1791201222723.jpg';
  const aiCardImage = '/src/assets/images/card_ai_neural_1791201234283.jpg';

  const dailyGoalMinutes = 50;
  const todayMinutes = stats.history.find(
    (h) => h.date === new Date().toISOString().split('T')[0]
  )?.minutes || 0;
  const progressPercent = Math.min(100, Math.round((todayMinutes / dailyGoalMinutes) * 100));

  return (
    <div className="space-y-12 pb-16">
      {/* Hero Section */}
      <section className="relative overflow-hidden rounded-3xl border border-stone-800 bg-[#161311] shadow-2xl">
        <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-8 p-8 sm:p-10 lg:p-12 items-center">
          <div className="lg:col-span-7 space-y-6">
            <div className="flex items-center gap-2 text-xs font-mono-numbers text-amber-400 font-semibold tracking-wide uppercase">
              <span className="flex h-2 w-2 rounded-full bg-amber-400 animate-ping" />
              <span>Cognitive Mastery & Deep Work Sanctuary</span>
            </div>

            <h1 className="font-display text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-stone-100 leading-[1.08] text-balance">
              Study smarter.<br />
              <span className="text-amber-400">Become unstoppable.</span>
            </h1>

            <p className="text-base sm:text-lg text-stone-400 max-w-xl leading-relaxed">
              Your personal study space. Eliminate friction with procedural ambient soundscapes,
              structured Markdown notes, and instant active recall quizzes generated by AI.
            </p>

            {/* Quick Action Buttons */}
            <div className="flex flex-wrap items-center gap-3 pt-2">
              <button
                onClick={() => onSelectTab('focus')}
                className="flex items-center gap-2 px-6 py-3 text-sm font-semibold text-stone-950 bg-amber-400 hover:bg-amber-300 rounded-xl transition-all shadow-lg shadow-amber-500/20 active:scale-95"
              >
                <Clock className="h-4 w-4" />
                <span>Enter Deep Focus</span>
              </button>
              <button
                onClick={() => onSelectTab('generator')}
                className="flex items-center gap-2 px-6 py-3 text-sm font-semibold text-stone-200 bg-stone-900/90 hover:bg-stone-800 border border-stone-700/80 rounded-xl transition-all active:scale-95"
              >
                <Brain className="h-4 w-4 text-amber-400" />
                <span>Generate AI Quiz</span>
              </button>
            </div>

            {/* Micro proof / daily goal bar */}
            <div className="pt-4 border-t border-stone-800/80 flex flex-wrap items-center gap-6 text-xs text-stone-400">
              <button
                onClick={() => onSelectTab('progress')}
                className="flex items-center gap-2 hover:text-amber-300 transition-colors"
                title="View Progress Dashboard"
              >
                <Flame className="h-4 w-4 text-amber-500 fill-amber-500/20" />
                <span className="font-semibold text-stone-200">{stats.streakDays} Day Streak</span>
              </button>
              <span className="text-stone-700">·</span>
              <button
                onClick={() => onSelectTab('progress')}
                className="flex items-center gap-2 hover:text-amber-300 transition-colors"
                title="View Progress Dashboard"
              >
                <Target className="h-4 w-4 text-amber-400" />
                <span>
                  Today: <strong className="text-stone-200 font-mono-numbers">{todayMinutes}m</strong> / {dailyGoalMinutes}m ({progressPercent}%) →
                </span>
              </button>
            </div>
          </div>

          {/* Hero Ambient Visual with Fallback */}
          <div className="lg:col-span-5 relative">
            <div className="relative aspect-[16/10] sm:aspect-[4/3] rounded-2xl overflow-hidden border border-stone-800/80 shadow-inner group">
              <img
                src={heroImage}
                alt="Cozy ambient study desk"
                referrerPolicy="no-referrer"
                className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                onError={(e) => {
                  e.currentTarget.style.display = 'none';
                  const fallback = e.currentTarget.parentElement?.querySelector('.image-fallback') as HTMLElement;
                  if (fallback) fallback.style.display = 'flex';
                }}
              />
              <div className="image-fallback hidden absolute inset-0 bg-gradient-to-br from-amber-950/40 via-stone-900 to-[#141210] flex-col items-center justify-center p-6 text-center">
                <Sparkles className="h-10 w-10 text-amber-400/80 mb-2" />
                <p className="text-sm font-display text-stone-200">StudySpace Sanctuary</p>
                <p className="text-xs text-stone-500">Distraction-free deep cognitive focus</p>
              </div>

              {/* Scrim Overlay */}
              <div className="absolute inset-0 bg-gradient-to-t from-stone-950/80 via-transparent to-transparent pointer-events-none" />

              <div className="absolute bottom-3 left-4 right-4 flex items-center justify-between text-xs text-stone-300">
                <span className="font-mono-numbers text-[11px] bg-stone-950/70 backdrop-blur-md px-2.5 py-1 rounded-md border border-stone-800">
                  ⚡ Web Audio Active
                </span>
                <span className="font-mono-numbers text-[11px] bg-stone-950/70 backdrop-blur-md px-2.5 py-1 rounded-md border border-stone-800">
                  🎯 Zero Distractions
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* The 3 Core Pillars (from User's Prototype) */}
      <section className="space-y-6">
        <div>
          <h2 className="font-display text-2xl font-bold tracking-tight text-stone-100">
            Core Study Engines
          </h2>
          <p className="text-sm text-stone-400 mt-1">
            Seamlessly flow between silent focus, organized note taking, and active recall testing.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Card 1: Deep Focus */}
          <div
            onClick={() => onSelectTab('focus')}
            className="group cursor-pointer rounded-2xl border border-stone-800 bg-[#171412] hover:bg-[#1e1a17] hover:border-amber-500/40 p-6 transition-all duration-300 shadow-md flex flex-col justify-between"
          >
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400 group-hover:scale-110 transition-transform">
                  <Clock className="h-6 w-6" />
                </div>
                <span className="text-xs font-mono-numbers text-stone-500 group-hover:text-amber-400 transition-colors">
                  01
                </span>
              </div>

              <div>
                <h3 className="text-xl font-bold text-stone-100 group-hover:text-amber-200 transition-colors">
                  🎯 Deep Focus
                </h3>
                <p className="text-sm text-stone-400 mt-2 leading-relaxed">
                  Focus without distractions using customized Pomodoro timers, task anchors, and procedural ambient audio (rain, cafe, 40Hz gamma waves).
                </p>
              </div>

              <div className="pt-2 flex flex-wrap gap-2 text-xs text-stone-400">
                <span className="bg-stone-900 px-2 py-0.5 rounded border border-stone-800">25m & 50m Presets</span>
                <span className="bg-stone-900 px-2 py-0.5 rounded border border-stone-800">Zen Fullscreen</span>
              </div>
            </div>

            <div className="pt-6 flex items-center text-sm font-semibold text-amber-400 group-hover:translate-x-1 transition-transform">
              <span>Open Timer</span>
              <ArrowRight className="h-4 w-4 ml-1.5" />
            </div>
          </div>

          {/* Card 2: My Notes */}
          <div
            onClick={() => onSelectTab('notes')}
            className="group cursor-pointer rounded-2xl border border-stone-800 bg-[#171412] hover:bg-[#1e1a17] hover:border-amber-500/40 p-6 transition-all duration-300 shadow-md flex flex-col justify-between"
          >
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400 group-hover:scale-110 transition-transform">
                  <BookOpen className="h-6 w-6" />
                </div>
                <span className="text-xs font-mono-numbers text-stone-500 group-hover:text-amber-400 transition-colors">
                  02
                </span>
              </div>

              <div>
                <h3 className="text-xl font-bold text-stone-100 group-hover:text-amber-200 transition-colors">
                  📝 My Notes
                </h3>
                <p className="text-sm text-stone-400 mt-2 leading-relaxed">
                  Keep your study notes structured with Markdown, organized by subjects, and ready to convert into AI quizzes with a single click.
                </p>
              </div>

              <div className="pt-2 flex flex-wrap gap-2 text-xs text-stone-400">
                <span className="bg-stone-900 px-2 py-0.5 rounded border border-stone-800">{notes.length} Active Notes</span>
                <span className="bg-stone-900 px-2 py-0.5 rounded border border-stone-800">AI Summaries</span>
              </div>
            </div>

            <div className="pt-6 flex items-center text-sm font-semibold text-amber-400 group-hover:translate-x-1 transition-transform">
              <span>Browse Notes</span>
              <ArrowRight className="h-4 w-4 ml-1.5" />
            </div>
          </div>

          {/* Card 3: AI Question Generator */}
          <div
            onClick={() => onSelectTab('generator')}
            className="group cursor-pointer rounded-2xl border border-stone-800 bg-[#171412] hover:bg-[#1e1a17] hover:border-amber-500/40 p-6 transition-all duration-300 shadow-md flex flex-col justify-between"
          >
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400 group-hover:scale-110 transition-transform">
                  <Brain className="h-6 w-6" />
                </div>
                <span className="text-xs font-mono-numbers text-stone-500 group-hover:text-amber-400 transition-colors">
                  03
                </span>
              </div>

              <div>
                <h3 className="text-xl font-bold text-stone-100 group-hover:text-amber-200 transition-colors">
                  🧠 AI Question Generator
                </h3>
                <p className="text-sm text-stone-400 mt-2 leading-relaxed">
                  Generate multiple choice questions, flashcards, or short answers from your material. Test yourself with live feedback and AI grading.
                </p>
              </div>

              <div className="pt-2 flex flex-wrap gap-2 text-xs text-stone-400">
                <span className="bg-stone-900 px-2 py-0.5 rounded border border-stone-800">Active Recall</span>
                <span className="bg-stone-900 px-2 py-0.5 rounded border border-stone-800">Instant Explanations</span>
              </div>
            </div>

            <div className="pt-6 flex items-center text-sm font-semibold text-amber-400 group-hover:translate-x-1 transition-transform">
              <span>Create Practice Quiz</span>
              <ArrowRight className="h-4 w-4 ml-1.5" />
            </div>
          </div>
        </div>
      </section>

      {/* Quick Launch Notes into Quiz */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-display text-xl font-bold text-stone-100">
              Ready to Practice: Your Study Material
            </h2>
            <p className="text-xs text-stone-400">
              Click &quot;Generate Quiz&quot; on any note to immediately create an active recall test.
            </p>
          </div>
          <button
            onClick={() => onSelectTab('notes')}
            className="text-xs font-semibold text-amber-400 hover:text-amber-300 flex items-center gap-1"
          >
            <span>View All Notes</span>
            <ArrowRight className="h-3.5 w-3.5" />
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {notes.slice(0, 3).map((note) => (
            <div
              key={note.id}
              className="rounded-xl border border-stone-800 bg-[#161311] p-5 flex flex-col justify-between hover:border-stone-700 transition-colors"
            >
              <div>
                <div className="flex items-center justify-between text-xs text-stone-400 mb-2">
                  <span className="font-semibold text-amber-400">{note.subject}</span>
                  <span className="font-mono-numbers">
                    {new Date(note.updatedAt).toLocaleDateString(undefined, {
                      month: 'short',
                      day: 'numeric',
                    })}
                  </span>
                </div>
                <h4 className="font-semibold text-stone-200 line-clamp-1">{note.title}</h4>
                <p className="text-xs text-stone-400 mt-2 line-clamp-2 leading-relaxed">
                  {note.content.replace(/[#*`_]/g, '')}
                </p>
              </div>

              <div className="pt-4 mt-4 border-t border-stone-800/80 flex items-center justify-between">
                <button
                  onClick={() => onSelectTab('notes')}
                  className="text-xs text-stone-400 hover:text-stone-200"
                >
                  Edit Note
                </button>
                <button
                  onClick={() => onOpenNoteForQuiz(note)}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-amber-500/10 hover:bg-amber-500/20 text-amber-300 text-xs font-semibold border border-amber-500/30 transition-all"
                >
                  <Brain className="h-3.5 w-3.5 text-amber-400" />
                  <span>Generate Quiz</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Active Study Insights Banner */}
      <section className="rounded-2xl border border-stone-800/80 bg-gradient-to-r from-stone-900 via-[#171412] to-amber-950/20 p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-start gap-4">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-500/20 text-amber-400 border border-amber-500/30">
            <Zap className="h-5 w-5" />
          </div>
          <div>
            <h3 className="font-semibold text-stone-200 text-sm">
              The Cognitive Science of Testing Effect
            </h3>
            <p className="text-xs text-stone-400 mt-1 max-w-2xl leading-relaxed">
              Passively re-reading notes yields under 20% long-term retention. Generating questions and testing yourself with active recall strengthens neural retrieval pathways and doubles memory durability.
            </p>
          </div>
        </div>

        <button
          onClick={() => onSelectTab('flashcards')}
          className="shrink-0 flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-stone-200 bg-stone-800 hover:bg-stone-700 rounded-lg border border-stone-700 transition-colors whitespace-nowrap"
        >
          <Layers className="h-3.5 w-3.5 text-amber-400" />
          <span>Practice Flashcards</span>
        </button>
      </section>
    </div>
  );
};
